# Generated by Django 4.2.3 on 2023-08-05 00:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('time_to_beat', models.TimeField(verbose_name='when it should be done,')),
                ('day_to_beat', models.DateField(default=datetime.date(2023, 8, 5), verbose_name='on what day need to be maden?')),
                ('important', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='how important the goal is (from 0 to 3)')),
                ('is_done', models.BooleanField(default=0, verbose_name='made?')),
                ('is_great', models.BooleanField(default=0, verbose_name='long-term goal?')),
                ('is_repeat', models.BooleanField(default=0, verbose_name='repeatable goal?')),
                ('repeat_every', models.IntegerField(default=0, verbose_name='repeat every')),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 5, 0, 14, 32, 746091, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
