# Generated by Django 4.2.3 on 2023-08-05 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 5, 0, 29, 29, 4629, tzinfo=datetime.timezone.utc)),
        ),
    ]
