# Generated by Django 4.2.3 on 2023-08-05 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_target_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 0, 38, 11, 88273, tzinfo=datetime.timezone.utc)),
        ),
    ]
