# Generated by Django 4.2.3 on 2023-08-05 22:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_target_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='day_to_beat',
            field=models.DateField(default=datetime.date(2023, 8, 6), verbose_name='on what day need to be maden?'),
        ),
        migrations.AlterField(
            model_name='target',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
