# Generated by Django 4.2.3 on 2023-08-05 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_target_day_to_beat_alter_target_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='important',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='how important the goal is (from 0 to 3)'),
        ),
    ]
