# Generated by Django 4.2.3 on 2023-08-08 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_target_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='pub_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='target',
            name='day_to_beat',
            field=models.DateField(default=datetime.date(2023, 8, 9), verbose_name='on what day need to be maden?'),
        ),
    ]
