# Generated by Django 4.2.3 on 2023-08-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_target_pub_day_alter_target_day_to_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='time_to_beat',
            field=models.TimeField(default='23:59', verbose_name='when it should be done'),
        ),
    ]
