# Generated by Django 4.2.3 on 2023-08-13 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_target_auxiliary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
